### ISSUE TITLE
No such file or directory: 'model/wangwen-2022-02-15.pth

### ISSUE THREAD

**Issue by kalvinGit** [BlinkDL/AI-Writer#12]
python run.py 报错：
说是找不到wangwen-2022-02-15.pth这个文件，但是下载下来的模型后缀是.onnx，并没有.pth后缀的。

```
Loading model for gpu... Traceback (most recent call last):
  File "run.py", line 90, in <module>
    m2 = torch.load(MODEL_NAME + '.pth', map_location='cpu').state_dict()
  File "C:\Users\14813\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\serialization.py", line 581, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\14813\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\14813\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'model/wangwen-2022-02-15.pth'
```

**Comment by BlinkDL** [comment]
下载N卡模型就是pth。A卡模型是onnx。
