### ISSUE TITLE
A卡 安装完第一次跑报错

### ISSUE THREAD

**Issue by huige728** [BlinkDL/AI-Writer#8]
用机环境win7 64位 ，e3 1230v2+hd6570，A卡驱动及管理器是安装好的
已经解决的安装问题：
1、c++库需是2019以上
2、pip install torch onnxruntime-directml是国外的源，下载太慢，要3个多小时，几kb-十几kb，转国内源就好下载

最后跑起来出现下图问题：

`Loading model for dml... Traceback (most recent call last):
File "d:/ai/AI writer main/run.py" line 81, in <module>
import onnxruntime as rt
File "C:\Users\huige\AppData\Local\Programs\Python\Python38\lib\site packages\onnxruntime\__init__ .py" line 55, in<module>
raise import_capi_exception
File "C: \Users\huige\AppData\Local\Prograns\Python\Python38\lib\site-packages\onnxruntime\__init__ .py", line 23, in <module>
from onnxruntime. capi._pybind_state import（
File "C: \Users\huige\AppData\Local\Programs\Python\Python38\lib\site-pacages\onnxruntime\capi\_pybind_ state.py", line 32, in <module>
from .onnxruntime_pybind11_state import  * # noqa
ImportError: DLL load failed while importing onxruntime_pybind11_state: 找不到指定的模块。
PS D:\ai\AI-Writer-main>`

**Comment by BlinkDL** [comment]
还需要win10最新21h2版，而且A卡至少需要RX6xxx。

**Comment by Sum41forever** [comment]
给个配置参考把，我也是用的A卡 RX580  win1022H2 能跑起来
![image](https://user-images.githubusercontent.com/18468976/209427562-71a0cb9c-54bf-45e1-b34a-5f18c221d400.png)
